### ISSUE TITLE
Bring this repo up to date with current work

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/interop#3]

**Comment by Mikerah** [comment]
Is there any updates on this? As we are preparing for a test network soon, we need to ensure our version of gossipsub has been implemented properly and interoperates with the other implementations.

**Comment by vasco-santos** [comment]
@Mikerah expect some progress on [libp2p/interop#4](https://github.com/libp2p/interop/pull/4]. 

[libp2p/js-libp2p-daemon](https://github.com/libp2p/js-libp2p-daemon) and [libp2p/js-libp2p-daemon-client](https://github.com/libp2p/js-libp2p-daemon-client) still do not support `pubsub`.  One the `libp2p-interop` setup tests are ready, I will add support for pubsub to them, in order to allow the `floodsub` and `gossibsub` interop tests in this repo.

**Comment by vasco-santos** [comment]
I am closing this issue, as the repo is now updated and has interop tests for the main functionalities. New interop tests will be added as new features land and the remaining ones will be finished soon.
