### ISSUE TITLE
Deflake tests

### ISSUE THREAD

**Issue by Stebalien** [libp2p/interop#48]
At least one of these tests is failing more often than not in GitHub Actions CI. We should investigate and fix this.

**Comment by Stebalien** [comment]
Take a look at the `Interop Tests / Js/Go` jobs in https://github.com/libp2p/go-libp2p/pulls. To debug:

1. Try running the interop tests locally. The readme includes instructions, but you can also just do what the action does: https://github.com/libp2p/go-libp2p/blob/master/.github/workflows/interop.yml.
2. Repeatedly run the action in CI (in go-libp2p). In a PR, disable all other CI jobs, and copy the last "run interop tests" step a few times. That way, you're guaranteed to get a failure.

**Comment by Stebalien** [comment]
NOTE: The tests may not be the issue, this could be due to a bug somewhere. But it's probably a test issue.

**Comment by Menduist** [comment]
For what it's worth, we also started to have flaky interop tests on `nim-libp2p` after upgrading to the latest version of `go-libp2p-daemon`
Actually, it's not even the interop tests which are failing, but the daemon test itself. Sometime, [this test](https://github.com/status-im/nim-libp2p/blob/1b2cdd6aec465e8066e71a9b1b164d985fcfc3a2/tests/testdaemon.nim#L106-L130) is failing, because, AFAICT, the two daemon successfully connects to each other, but they fail to form a mesh on the "test-topic".

It would be nice to coordinate our interop tests. Since `go-libp2p-daemon` is deprecated, we are thinking about using a in-house utility instead for our interop tests, but if the plan is to keep it in working condition for the interop tests that would be great, and we could think about creating a `nim-libp2p-daemon` to integrate here

**Comment by Stebalien** [comment]
Note: go-libp2p-daemon isn't being maintained user-facing tool, but it
isn't deprecated for the purposes of testing.

**Comment by achingbrain** [comment]
The flaky test in question was not recorded above, and the logs of the linked CI runs have long since expired, but the pubsub tests here were occasionally flaky due to arbitrary timeouts being set in the code instead of testing for the actual thing it was waiting for.

This has been fixed in https://github.com/libp2p/interop/pull/88 so I'm going to close this issue.  I will open a new one if further flakiness is observed.
